name: Create GCP Bucket
on:
  workflow_dispatch: # Esto te permite ejecutarlo manualmente desde la web de GitHub

jobs:
  manage-storage:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Create Storage Bucket'
        run: |
          # Intentará crear el bucket si no existe. 
          # El nombre será: bucket-tu-id-de-proyecto
          gsutil mb -l us-central1 gs://bucket-${{ secrets.GCP_PROJECT_ID }} || echo "El bucket ya existe o no se pudo crear"
